/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFreezable,
  IFreezableInterface,
} from "../../../../contracts/governance/GuardianCouncil.sol/IFreezable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "freezeUntil",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unfreeze",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFreezable__factory {
  static readonly abi = _abi;
  static createInterface(): IFreezableInterface {
    return new Interface(_abi) as IFreezableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFreezable {
    return new Contract(address, _abi, runner) as unknown as IFreezable;
  }
}
