/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as guardianCouncilSol from "./GuardianCouncil.sol";
export type { guardianCouncilSol };
import type * as timelockControllerSol from "./TimelockController.sol";
export type { timelockControllerSol };
export type { GovernorDAO } from "./GovernorDAO";
