#!/bin/bash

# Gemini CLI Complete VetSorcery Code Review Script
# This script performs a comprehensive analysis of the entire VetSorcery codebase

echo "🔍 Starting Gemini CLI Complete VetSorcery Code Review..."
echo "=================================================="

# Set up variables
PROJECT_ROOT="/Users/studio/hardcard/HARDCARDSUITE/vetsorcery_extracted"
BACKEND_DIR="$PROJECT_ROOT/backend"
FRONTEND_DIR="$PROJECT_ROOT/frontend"
REVIEW_OUTPUT="gemini_vetsorcery_review_$(date +%Y%m%d_%H%M%S).md"

# Initialize review report
cat > "$REVIEW_OUTPUT" << 'EOF'
# VetSorcery Complete Code Review Report

Generated by Gemini CLI on $(date)

## Executive Summary

This comprehensive review analyzes the VetSorcery veterinary management system for:
- Architecture & Design Patterns
- Security Vulnerabilities
- Code Quality & Best Practices
- API Design & Documentation
- Database Schema & Performance
- Frontend Interactivity & UX
- Module Functionality Depth
- Production Readiness

EOF

# Function to analyze with Gemini
analyze_with_gemini() {
    local context=$1
    local files=$2
    local prompt=$3
    
    echo "Analyzing: $context"
    
    if command -v gemini >/dev/null 2>&1; then
        gemini chat -c "$files" -p "$prompt" >> "$REVIEW_OUTPUT" 2>/dev/null
    else
        echo "⚠️  Gemini CLI not found. Please install: gem install gemini-cli"
    fi
}

# 1. Architecture & Design Review
echo -e "\n## 1. Architecture & Design Patterns Review\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Backend Architecture" "$BACKEND_DIR" \
"Review the FastAPI backend architecture for VetSorcery. Analyze:
1. Project structure and modularity
2. Separation of concerns
3. API design patterns
4. Dependency injection usage
5. Code organization
Focus on veterinary-specific modules: Standards, Tutorials, Workflows, HR Toolkit"

# 2. Security Analysis
echo -e "\n## 2. Security Vulnerability Analysis\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Security Review" "$BACKEND_DIR" \
"Perform a comprehensive security audit for VetSorcery:
1. Authentication & Authorization flaws
2. SQL injection vulnerabilities
3. XSS and CSRF protection
4. API security (rate limiting, CORS)
5. Sensitive data exposure
6. HIPAA compliance for veterinary records
7. Input validation gaps
Provide severity ratings and remediation steps"

# 3. Frontend Functionality Analysis
echo -e "\n## 3. Frontend Interactive Functionality Review\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Frontend Modules" "$FRONTEND_DIR/src/pages" \
"Review the VetSorcery frontend pages for full interactive functionality:
1. Standards of Care page - must have searchable standards, categories, version control
2. How-To Tutorials page - needs video support, step tracking, comments
3. Workflow Templates page - requires drag-drop editor, custom workflows
4. HR Toolkit page - needs forms, documents, training tracking
5. Dashboard interactivity - real-time updates, charts, notifications
Identify missing features and provide implementation code"

# 4. API Completeness Review
echo -e "\n## 4. API Endpoint Functionality Review\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "API Endpoints" "$BACKEND_DIR/app/apis" \
"Analyze VetSorcery API endpoints for complete functionality:
1. Standards API - CRUD operations, versioning, categories
2. Tutorials API - media upload, progress tracking, ratings
3. Workflows API - template management, execution tracking
4. HR Toolkit API - document management, training records
5. Missing endpoints for full functionality
Provide FastAPI code for missing endpoints"

# 5. Database Schema Analysis
echo -e "\n## 5. Database Schema & Data Model Review\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Database Models" "$BACKEND_DIR/app/database" \
"Review VetSorcery database schema for completeness:
1. Standards table - versions, categories, compliance tracking
2. Tutorials table - media references, user progress
3. Workflows table - steps, conditions, assignments
4. HR records - certifications, training, documents
5. Relationships and constraints
6. Missing tables for full functionality
Provide SQLAlchemy models for improvements"

# 6. Frontend Component Analysis
echo -e "\n## 6. React Component Functionality Review\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "React Components" "$FRONTEND_DIR/src/components" \
"Analyze VetSorcery React components for interactivity:
1. StandardsViewer - search, filter, version compare
2. TutorialPlayer - video controls, progress tracking
3. WorkflowBuilder - drag-drop, conditions, validation
4. HRDashboard - document upload, training calendar
5. Missing components for full functionality
Provide React/TypeScript code for enhancements"

# 7. Integration Testing Requirements
echo -e "\n## 7. Integration Testing Strategy\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Testing Strategy" "$PROJECT_ROOT" \
"Design comprehensive testing for VetSorcery modules:
1. Standards API integration tests
2. Tutorial progress tracking tests
3. Workflow execution tests
4. HR document management tests
5. End-to-end user flows
6. Performance benchmarks
Provide pytest and Jest test examples"

# 8. Performance Optimization
echo -e "\n## 8. Performance & Scalability Analysis\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Performance" "$BACKEND_DIR" \
"Analyze VetSorcery performance for veterinary clinic scale:
1. API response times for large datasets
2. Frontend rendering optimization
3. Database query optimization
4. Caching strategies for standards/tutorials
5. Media file handling for tutorials
6. Concurrent user handling
Provide optimization code"

# 9. UX Enhancement Review
echo -e "\n## 9. User Experience Enhancement Review\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "UX Analysis" "$FRONTEND_DIR" \
"Review VetSorcery UX for veterinary staff usability:
1. Standards search and navigation flow
2. Tutorial learning path progression
3. Workflow template customization
4. HR document accessibility
5. Mobile responsiveness
6. Accessibility compliance
Provide UI/UX improvement code"

# 10. Module-Specific Functionality
echo -e "\n## 10. Module-Specific Deep Functionality\n" >> "$REVIEW_OUTPUT"

# Standards Module
echo -e "\n### Standards of Care Module\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Standards Module" "$BACKEND_DIR/app/apis/standards" \
"Design complete Standards of Care functionality:
1. Hierarchical category system (species, procedures, conditions)
2. Version control with change tracking
3. Compliance reporting and auditing
4. Quick reference cards
5. Integration with EMR
6. Printable protocols
Provide implementation code"

# Tutorials Module
echo -e "\n### How-To Tutorials Module\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Tutorials Module" "$BACKEND_DIR/app/apis/tutorials" \
"Design complete Tutorial functionality:
1. Video hosting and streaming
2. Step-by-step progress tracking
3. Quiz and assessment integration
4. Bookmarking and notes
5. Skill certification tracking
6. Offline download capability
Provide implementation code"

# Workflows Module
echo -e "\n### Workflow Templates Module\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "Workflows Module" "$BACKEND_DIR/app/apis/workflows" \
"Design complete Workflow functionality:
1. Visual workflow builder
2. Conditional logic and branching
3. Role-based task assignment
4. Progress tracking and alerts
5. Template library management
6. Integration with scheduling
Provide implementation code"

# HR Toolkit Module
echo -e "\n### HR Toolkit Module\n" >> "$REVIEW_OUTPUT"
analyze_with_gemini "HR Module" "$BACKEND_DIR/app/apis/hr_toolkit" \
"Design complete HR Toolkit functionality:
1. Employee onboarding workflows
2. Training record management
3. Certification tracking and alerts
4. Performance review system
5. Document templates and forms
6. Time-off management
Provide implementation code"

# Generate Implementation Plan
echo -e "\n## Implementation Roadmap\n" >> "$REVIEW_OUTPUT"
echo "Based on the analysis above, here's the implementation priority:" >> "$REVIEW_OUTPUT"
echo "1. **Phase 1**: Security hardening and authentication" >> "$REVIEW_OUTPUT"
echo "2. **Phase 2**: Complete API endpoints for all modules" >> "$REVIEW_OUTPUT"
echo "3. **Phase 3**: Interactive frontend components" >> "$REVIEW_OUTPUT"
echo "4. **Phase 4**: Integration and testing" >> "$REVIEW_OUTPUT"
echo "5. **Phase 5**: Performance optimization" >> "$REVIEW_OUTPUT"
echo "6. **Phase 6**: Production deployment" >> "$REVIEW_OUTPUT"

# Summary
echo -e "\n---\n"
echo "✅ Gemini VetSorcery Review Complete!"
echo "📄 Review saved to: $REVIEW_OUTPUT"
echo ""
echo "Key Areas Requiring Immediate Attention:"
echo "1. Module functionality depth - each module needs complete CRUD operations"
echo "2. Interactive UI components - drag-drop, real-time updates, media players"
echo "3. Security implementation - authentication, authorization, audit trails"
echo "4. Integration points - EMR, scheduling, billing connections"
echo ""
echo "Next step: Run ./gemini_code_refinement.sh to implement improvements"