/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SchemaFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createSchema"
      | "deactivateSchema"
      | "freezeUntil"
      | "freezeUntilTimestamp"
      | "owner"
      | "reactivateSchema"
      | "renounceOwnership"
      | "schemaCount"
      | "schemas"
      | "transferOwnership"
      | "unfreeze"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "SchemaCreated"
      | "SchemaDeactivated"
      | "SchemaReactivated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createSchema",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateSchema",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeUntil",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeUntilTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateSchema",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "schemaCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "schemas", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unfreeze", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createSchema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateSchema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeUntil",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeUntilTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateSchema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "schemaCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schemas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unfreeze", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SchemaCreatedEvent {
  export type InputTuple = [
    schemaId: BytesLike,
    name: string,
    creator: AddressLike
  ];
  export type OutputTuple = [schemaId: string, name: string, creator: string];
  export interface OutputObject {
    schemaId: string;
    name: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SchemaDeactivatedEvent {
  export type InputTuple = [schemaId: BytesLike];
  export type OutputTuple = [schemaId: string];
  export interface OutputObject {
    schemaId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SchemaReactivatedEvent {
  export type InputTuple = [schemaId: BytesLike];
  export type OutputTuple = [schemaId: string];
  export interface OutputObject {
    schemaId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SchemaFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SchemaFactory;
  waitForDeployment(): Promise<this>;

  interface: SchemaFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSchema: TypedContractMethod<
    [name: string, uri: string],
    [string],
    "nonpayable"
  >;

  deactivateSchema: TypedContractMethod<
    [schemaId: BytesLike],
    [void],
    "nonpayable"
  >;

  freezeUntil: TypedContractMethod<
    [timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  freezeUntilTimestamp: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  reactivateSchema: TypedContractMethod<
    [schemaId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  schemaCount: TypedContractMethod<[], [bigint], "view">;

  schemas: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean] & {
        name: string;
        uri: string;
        creator: string;
        active: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unfreeze: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSchema"
  ): TypedContractMethod<[name: string, uri: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateSchema"
  ): TypedContractMethod<[schemaId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "freezeUntil"
  ): TypedContractMethod<[timestamp: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "freezeUntilTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateSchema"
  ): TypedContractMethod<[schemaId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "schemaCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "schemas"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean] & {
        name: string;
        uri: string;
        creator: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfreeze"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SchemaCreated"
  ): TypedContractEvent<
    SchemaCreatedEvent.InputTuple,
    SchemaCreatedEvent.OutputTuple,
    SchemaCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SchemaDeactivated"
  ): TypedContractEvent<
    SchemaDeactivatedEvent.InputTuple,
    SchemaDeactivatedEvent.OutputTuple,
    SchemaDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "SchemaReactivated"
  ): TypedContractEvent<
    SchemaReactivatedEvent.InputTuple,
    SchemaReactivatedEvent.OutputTuple,
    SchemaReactivatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SchemaCreated(bytes32,string,address)": TypedContractEvent<
      SchemaCreatedEvent.InputTuple,
      SchemaCreatedEvent.OutputTuple,
      SchemaCreatedEvent.OutputObject
    >;
    SchemaCreated: TypedContractEvent<
      SchemaCreatedEvent.InputTuple,
      SchemaCreatedEvent.OutputTuple,
      SchemaCreatedEvent.OutputObject
    >;

    "SchemaDeactivated(bytes32)": TypedContractEvent<
      SchemaDeactivatedEvent.InputTuple,
      SchemaDeactivatedEvent.OutputTuple,
      SchemaDeactivatedEvent.OutputObject
    >;
    SchemaDeactivated: TypedContractEvent<
      SchemaDeactivatedEvent.InputTuple,
      SchemaDeactivatedEvent.OutputTuple,
      SchemaDeactivatedEvent.OutputObject
    >;

    "SchemaReactivated(bytes32)": TypedContractEvent<
      SchemaReactivatedEvent.InputTuple,
      SchemaReactivatedEvent.OutputTuple,
      SchemaReactivatedEvent.OutputObject
    >;
    SchemaReactivated: TypedContractEvent<
      SchemaReactivatedEvent.InputTuple,
      SchemaReactivatedEvent.OutputTuple,
      SchemaReactivatedEvent.OutputObject
    >;
  };
}
